### ISSUE TITLE
POP staking amount spasms

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/sweet-caramel#639] opened 2022-04-27 20:36 UTC
Expected: POP staking amount should be displayed without any visual glitching 

Observed: Every three seconds, POP staking flashes to 0 and says 'insufficient balance'

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/d03e9c94-1df7-4265-9d06-d1ff7d91e2a4)

System: windows, firefox, metamask, build 630, pop staking page

Steps: go to staking page and enter any amount of pop

**Comment by arne-z** [comment] 2022-04-28 09:29
This appears to be a duplicate of https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/614

**Closed by arne-z** 2022-04-28 09:29 UTC
Labels: bug
